# Imports

In [1]:
import os
import pickle
import re
import shutil
import sys
sys.path.append(os.path.dirname(os.getcwd()))
from itertools import product

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import yaml
from matplotlib.backends.backend_pdf import PdfPages
from tools import load_npy, load_yaml_as_df, load_pkl, exist_metric, exist_stf_metric, inverse_stf_metrics, keep_split, is_full_group

plt.style.use('default')
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42
plt.rc('font', family='Arial')
matplotlib.rcParams['mathtext.fontset'] = 'stix'
matplotlib.rcParams['font.size'] = 10

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Baselines

## load data

In [2]:
root = '/data/home/Licheng/workspace/TSF-PCA/results_PCA/baselines'
exp_dirs = os.listdir(root)
exp_dirs = [os.path.join(root, exp_dir) for exp_dir in exp_dirs]

params = ['model', 'pred_len', 'data_id', 'learning_rate', 'batch_size', 'patience', 'individual', 'train_epochs', 'lradj']
metric_names = ['mse', 'mae']

df = []
for exp_dir in exp_dirs:
    runned, setting_dir = exist_metric(exp_dir)
    if not runned:
        continue

    config = load_yaml_as_df(os.path.join(setting_dir, 'config.yaml'))
    metric = load_npy(os.path.join(setting_dir, 'metrics.npy'))
    result = config[params]
    model, individual = config['model'].values[0], config['individual'].values[0]
    if model == 'DLinear' and individual:
        result['model'].values[0] = 'DLinear_Ind'
    result.loc[:, metric_names] = metric[1], metric[0]
    result.loc[:, ['exp_dir']] = exp_dir
    df.append(result)

df = pd.concat(df, ignore_index=True)
df.sort_values(by=['model', 'data_id', 'pred_len'], inplace=True)

save_root = '/data/home/Licheng/workspace/TSF-PCA/stats_PCA'
df.to_csv(f"{save_root}/baseline_all_results.csv", index=False)

df.head(4)

,model,pred_len,data_id,learning_rate,batch_size,patience,individual,train_epochs,lradj,mse,mae,exp_dir
1039,Autoformer,96,ECL,0.0005,32,3,0,10,type1,0.188511,0.303782,/data/home/Licheng/workspace/TSF-PCA/results_P...
627,Autoformer,192,ECL,0.0005,32,3,0,10,type1,0.270894,0.370508,/data/home/Licheng/workspace/TSF-PCA/results_P...
1138,Autoformer,336,ECL,0.0005,32,3,0,10,type1,0.242762,0.352282,/data/home/Licheng/workspace/TSF-PCA/results_P...
89,Autoformer,720,ECL,0.0005,32,3,0,10,type1,0.294784,0.388354,/data/home/Licheng/workspace/TSF-PCA/results_P...

## analysis

In [3]:
min_mode = 'each'

df2 = df.copy()

columns = ['model', 'data_id', 'learning_rate', 'batch_size', 'patience', 'individual', 'train_epochs']
if min_mode == 'group':
    mse_mean = df2.groupby(columns)['mse'].mean().reset_index()
    idx = mse_mean.groupby(['model', 'data_id'])['mse'].idxmin()
    best_model = mse_mean.loc[idx]
    df2 = df2.merge(best_model[columns], on=columns, how='inner')
elif min_mode == 'each':
    min_mse_idx = df2.groupby(['model', 'data_id', 'pred_len'])['mse'].idxmin()
    df2 = df2.loc[min_mse_idx]

save_root = '/data/home/Licheng/workspace/TSF-PCA/stats_PCA'
df2.to_csv(f'{save_root}/baselines_params.csv', index=False)

df2 = df2[['model', 'pred_len', 'data_id', 'mse', 'mae']]

dst_order = ['ETTm1', 'ETTm2', 'ETTh1', 'ETTh2', 'ECL', 'Traffic', 'Weather', 'PEMS03', 'PEMS08']
df2['data_id'] = pd.Categorical(df2['data_id'], categories=dst_order, ordered=True)

model_order = ['Fredformer', 'FBM_L', 'iTransformer', 'FreTS', 'TimesNet', 'MICN', 'TiDE', 'DLinear', 'DLinear_Ind', 'FEDformer', 'Autoformer', 'Transformer', 'TCN']
df2['model'] = pd.Categorical(df2['model'], categories=model_order, ordered=True)

df2_avg = df2.groupby(['model', 'data_id']).mean(numeric_only=True).reset_index()
df2_avg['pred_len'] = 'Avg'
df2 = pd.concat([df2, df2_avg]).reset_index(drop=True)

df2.sort_values(by=['model', 'data_id', 'pred_len'], inplace=True)

df2 = df2.set_index(['data_id', 'pred_len', 'model']).unstack('model').swaplevel(axis=1)
columns = []
for model in df2.columns.levels[0]:
    columns.append((model, 'mse'))
    columns.append((model, 'mae'))
df2 = df2[columns]

df2.to_excel(f'{save_root}/baselines.xlsx')
df2.to_csv(f'{save_root}/baselines.csv')
df2

/tmp/ipykernel_3645157/2609304744.py:26: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df2_avg = df2.groupby(['model', 'data_id']).mean(numeric_only=True).reset_index()

model            Fredformer               FBM_L           iTransformer  \
                        mse       mae       mse       mae          mse
data_id pred_len
ETTm1   96         0.326369  0.360869  0.349528  0.371773     0.337877
        192        0.365194  0.382132  0.390812  0.392347     0.381666
        336        0.395987  0.404369  0.422590  0.412849     0.426993
        720        0.459217  0.444342  0.485965  0.448586     0.495750
        Avg        0.386692  0.397928  0.412224  0.406389     0.410572
ETTm2   96         0.177032  0.259926  0.181807  0.264386     0.181968
        192        0.241639  0.299673  0.246169  0.304308     0.257024
        336        0.301849  0.340199  0.306986  0.342475     0.319923
        720        0.398819  0.396739  0.406963  0.397420     0.422518
        Avg        0.279835  0.324134  0.285481  0.327147     0.295358
ETTh1   96         0.377193  0.395888  0.383165  0.393112     0.385231
        192        0.437019  0.425390  0.433448  0.422649     0.440491
        336        0.485769  0.448580  0.474278  0.444622     0.479858
        720        0.487772  0.467352  0.463483  0.461765     0.503538
        Avg        0.446938  0.434302  0.438593  0.430537     0.452279
ETTh2   96         0.293376  0.343882  0.288704  0.337401     0.301348
        192        0.371951  0.391174  0.374276  0.389515     0.383043
        336        0.420394  0.433487  0.413145  0.424124     0.424908
        720        0.420675  0.439153  0.416531  0.436278     0.436269
        Avg        0.376599  0.401924  0.373164  0.396829     0.386392
ECL     96         0.161018  0.257591  0.197358  0.273776     0.150035
        192        0.173585  0.269470  0.197128  0.276295     0.168114
        336        0.194108  0.290397  0.211755  0.291585     0.182346
        720        0.234672  0.319384  0.253368  0.324154     0.214451
        Avg        0.190846  0.284211  0.214902  0.291452     0.178736
Traffic 96         0.460576  0.327217  0.645200  0.382956     0.396554
        192        0.469513  0.325797  0.597817  0.359186     0.415822
        336        0.491848  0.338340  0.605160  0.361769     0.429438
        720        0.521307  0.352766  0.642555  0.381331     0.462221
        Avg        0.485811  0.336030  0.622683  0.371311     0.426009
Weather 96         0.180192  0.219763  0.194073  0.233393     0.171432
        192        0.222379  0.257628  0.240332  0.270332     0.246395
        336        0.283492  0.300976  0.291561  0.306318     0.296230
        720        0.357656  0.348500  0.363714  0.352717     0.362297
        Avg        0.260930  0.281717  0.272420  0.290690     0.269089
PEMS03  12         0.080544  0.191345  0.116822  0.225549     0.072155
        24         0.120853  0.239561  0.233354  0.321429     0.104247
        36         0.180330  0.292452  0.378731  0.419020     0.137279
        48         0.201483  0.315661  0.534499  0.514812     0.173674
        Avg        0.145803  0.259755  0.315851  0.370203     0.121839
PEMS08  12         0.090728  0.198661  0.120719  0.231072     0.083674
        24         0.138053  0.245493  0.232158  0.326810     0.123175
        36         0.199214  0.303334  0.376393  0.425502     0.169713
        48         0.254821  0.338272  0.543686  0.525740     0.218126
        Avg        0.170704  0.271440  0.318239  0.377281     0.148672

model                          FreTS            TimesNet                MICN  \
                       mae       mse       mae       mse       mae       mse
data_id pred_len
ETTm1   96        0.372283  0.341839  0.374557  0.367581  0.394326  0.319464
        192       0.396060  0.384536  0.400407  0.406042  0.409226  0.364399
        336       0.423962  0.415986  0.420578  0.453587  0.443846  0.395255
        720       0.462558  0.513302  0.489186  0.526723  0.474275  0.505451
        Avg       0.413716  0.413916  0.421182  0.438483  0.430418  0.396142
ETTm2   96        0.264672  0.188369  0.278704  0.184397  0.261989  0.178366
        192       0.314782  0.264171  0.329131  0.257008  0.308367  0.266175
        336       0.353982  0.322375  0.369159  0.314522  0.344753  0.298865
        720       0.411374  0.489048  0.481541  0.452051  0.421373  0.489324
        Avg       0.336203  0.315991  0.364634  0.301994  0.334121  0.308182
ETTh1   96        0.405311  0.398209  0.409343  0.398867  0.418350  0.381327
        192       0.436761  0.450887  0.442458  0.452477  0.450616  0.497472
        336       0.457185  0.500554  0.471565  0.487951  0.468940  0.588631
        720       0.491569  0.607695  0.570694  0.549261  0.514712  0.664939
        Avg       0.447707  0.489336  0.473515  0.472139  0.463155  0.533093
ETTh2   96        0.349246  0.315258  0.373622  0.320652  0.358081  0.350985
        192       0.397185  0.466078  0.466572  0.417934  0.417311  0.492325
        336       0.432255  0.521734  0.501890  0.463911  0.454156  0.655967
        720       0.448485  0.792038  0.642590  0.434253  0.449573  0.980621
        Avg       0.406793  0.523777  0.496169  0.409188  0.419780  0.619974
ECL     96        0.241510  0.179914  0.266321  0.169621  0.272173  0.170347
        192       0.259067  0.184191  0.272484  0.182853  0.282249  0.184672
        336       0.274355  0.199205  0.289670  0.202699  0.301912  0.189831
        720       0.303504  0.234371  0.321930  0.293821  0.366023  0.221404
        Avg       0.269609  0.199420  0.287601  0.212249  0.305589  0.191564
Traffic 96        0.271166  0.531422  0.323299  0.589990  0.316052  0.498462
        192       0.278879  0.518544  0.321419  0.624264  0.336368  0.520604
        336       0.285957  0.529182  0.327432  0.641338  0.345160  0.529479
        720       0.302825  0.573215  0.345998  0.670208  0.356389  0.567289
        Avg       0.284707  0.538091  0.329537  0.631450  0.338492  0.528958
Weather 96        0.210468  0.173683  0.227737  0.182825  0.229222  0.178838
        192       0.278306  0.212846  0.266092  0.242126  0.276198  0.241920
        336       0.312968  0.270492  0.315915  0.292737  0.311621  0.272896
        720       0.352779  0.337221  0.362299  0.366493  0.361353  0.360350
        Avg       0.288630  0.248560  0.293011  0.271045  0.294599  0.263501
PEMS03  12        0.179175  0.085341  0.197743  0.094102  0.201451  0.096175
        24        0.216657  0.128960  0.243670  0.116147  0.220572  0.094863
        36        0.251307  0.172993  0.285870  0.133833  0.236715  0.106963
        48        0.284689  0.206860  0.315118  0.161368  0.261545  0.124820
        Avg       0.232957  0.148539  0.260600  0.126363  0.230071  0.105705
PEMS08  12        0.187030  0.096209  0.205204  0.111144  0.208477  0.161016
        24        0.226933  0.150558  0.258306  0.138578  0.231777  0.126638
        36        0.268113  0.203116  0.302906  0.168344  0.259766  0.147889
        48        0.306091  0.246853  0.334388  0.188913  0.271932  0.174629
        Avg       0.247042  0.174184  0.275201  0.151745  0.242988  0.152543

model                           TiDE             DLinear            \
                       mae       mse       mae       mse       mae
data_id pred_len
ETTm1   96        0.365535  0.352875  0.374209  0.345850  0.373350
        192       0.395440  0.391134  0.392581  0.380310  0.389934
        336       0.425257  0.423440  0.413670  0.413243  0.413936
        720       0.498788  0.485727  0.447867  0.471745  0.449863
        Avg       0.421255  0.413294  0.407082  0.402787  0.406771
ETTm2   96        0.276882  0.182171  0.264981  0.187883  0.282945
        192       0.343027  0.246520  0.304153  0.279695  0.355772
        336       0.354177  0.307372  0.342926  0.375375  0.420250
        720       0.481615  0.407665  0.398233  0.525772  0.508116
        Avg       0.363925  0.285932  0.327573  0.342181  0.391771
ETTh1   96        0.416093  0.386880  0.394970  0.388942  0.403672
        192       0.488515  0.438658  0.424741  0.442218  0.439876
        336       0.555285  0.481754  0.446970  0.488474  0.466596
        720       0.617057  0.483673  0.471415  0.505058  0.502427
        Avg       0.519238  0.447741  0.434524  0.456173  0.453143
ETTh2   96        0.397604  0.290839  0.339774  0.330024  0.382585
        192       0.488659  0.376183  0.391642  0.439167  0.449528
        336       0.581570  0.416813  0.427378  0.589380  0.537515
        720       0.717740  0.429363  0.445574  0.757178  0.626219
        Avg       0.546394  0.378299  0.401092  0.528937  0.498962
ECL     96        0.281227  0.197488  0.274012  0.197025  0.282377
        192       0.297435  0.197295  0.276812  0.196554  0.285564
        336       0.297954  0.211890  0.291828  0.209465  0.300937
        720       0.329447  0.253835  0.325082  0.244849  0.333502
        Avg       0.301516  0.215127  0.291933  0.211973  0.300595
Traffic 96        0.298258  0.646293  0.385530  0.648851  0.396575
        192       0.309233  0.599241  0.361613  0.598479  0.370914
        336       0.313973  0.605791  0.363088  0.605241  0.373328
        720       0.326198  0.642768  0.382508  0.645800  0.395380
        Avg       0.311916  0.623523  0.373185  0.624593  0.384049
Weather 96        0.244204  0.191614  0.232393  0.193972  0.253232
        192       0.310061  0.239818  0.270194  0.237857  0.296273
        336       0.330184  0.292499  0.306784  0.281825  0.332035
        720       0.399060  0.364291  0.353228  0.347499  0.384916
        Avg       0.320877  0.272055  0.290650  0.265288  0.316614
PEMS03  12        0.216982  0.116850  0.225791  0.105025  0.220418
        24        0.209643  0.233325  0.322048  0.182893  0.296870
        36        0.222906  0.378858  0.417677  0.257679  0.361320
        48        0.242245  0.535149  0.516158  0.318706  0.410237
        Avg       0.222944  0.316045  0.370418  0.216076  0.322211
PEMS08  12        0.274249  0.120960  0.233324  0.112962  0.225221
        24        0.236966  0.232394  0.325121  0.198670  0.302117
        36        0.252121  0.376292  0.427015  0.294509  0.370639
        48        0.269627  0.543399  0.526627  0.388941  0.428529
        Avg       0.258241  0.318261  0.378022  0.248770  0.331627

model            DLinear_Ind           FEDformer           Autoformer  \
                         mse       mae       mse       mae        mse
data_id pred_len
ETTm1   96          0.329154  0.363183  0.400846  0.433660   0.485350
        192         0.366471  0.381432  0.414898  0.446424   0.504394
        336         0.396187  0.401638  0.431819  0.449567   0.519575
        720         0.460491  0.438445  0.522394  0.500073   0.594124
        Avg         0.388076  0.396174  0.442489  0.457431   0.525861
ETTm2   96          0.236243  0.319987  0.205485  0.289068   0.217674
        192         0.401435  0.409858  0.270690  0.334417   0.281957
        336         0.576191  0.502070  0.327179  0.365933   0.335499
        720         1.005530  0.657234  0.427742  0.425203   0.422951
        Avg         0.554850  0.472287  0.307774  0.353655   0.314520
ETTh1   96          0.386798  0.398507  0.391024  0.432856   0.448748
        192         0.445934  0.434416  0.417686  0.448253   0.458649
        336         0.485546  0.453285  0.487055  0.484445   0.510600
        720         0.503780  0.488704  0.494175  0.513733   0.488103
        Avg         0.455514  0.443728  0.447485  0.469822   0.476525
ETTh2   96          0.569977  0.489148  0.351419  0.390817   0.355386
        192         0.803599  0.587651  0.456231  0.455651   0.478403
        336         1.015242  0.668045  0.477129  0.491711   0.458667
        720         1.231125  0.750737  0.522159  0.505372   0.499368
        Avg         0.904986  0.623895  0.451734  0.460887   0.447956
ECL     96          0.188159  0.277768  0.186723  0.302100   0.188511
        192         0.188420  0.281049  0.206940  0.321890   0.270894
        336         0.201845  0.296435  0.210639  0.326482   0.242762
        720         0.237738  0.328947  0.252541  0.361444   0.294784
        Avg         0.204040  0.296050  0.214211  0.327979   0.249238
Traffic 96          0.647961  0.404133  0.588221  0.366911   0.574563
        192         0.602892  0.377349  0.613475  0.376783   0.647053
        336         0.608546  0.379254  0.639525  0.397734   0.693875
        720         0.647320  0.400089  0.717820  0.450032   0.731273
        Avg         0.626680  0.390206  0.639760  0.397865   0.661691
Weather 96          0.164179  0.237422  0.234548  0.310107   0.232605
        192         0.205963  0.278936  0.294910  0.352756   0.285512
        336         0.260636  0.324074  0.364093  0.396839   0.346095
        720         0.337649  0.378768  0.411113  0.428502   0.411735
        Avg         0.242107  0.304800  0.326166  0.372051   0.318987
PEMS03  12          0.102118  0.219256  0.108452  0.228628   0.232775
        24          0.175601  0.293618  0.130944  0.254584   0.405249
        36          0.246707  0.356206  0.159222  0.284987   0.327151
        48          0.305715  0.404454  0.209092  0.331001   0.679448
        Avg         0.207535  0.318384  0.151928  0.274800   0.411156
PEMS08  12          0.119492  0.230465  0.162519  0.257734   0.231731
        24          0.204621  0.305512  0.197078  0.287584   0.544626
        36          0.296822  0.371291  0.241189  0.326235   0.378649
        48          0.387607  0.425950  0.302010  0.375117   0.531148
        Avg         0.252135  0.333305  0.225699  0.311668   0.421538

model                      Transformer                 TCN
                       mae         mse       mae       mse       mae
data_id pred_len
ETTm1   96        0.468443    0.502876  0.481508  0.886832  0.613308
        192       0.481982    0.806969  0.663956  0.875331  0.625851
        336       0.489404    0.847205  0.677553  0.888828  0.635628
        720       0.523401    1.037406  0.770681  0.905373  0.649468
        Avg       0.490807    0.798614  0.648424  0.889091  0.631064
ETTm2   96        0.300010    0.385733  0.440774  3.124491  1.344850
        192       0.340410    1.409554  0.881172  3.133993  1.349833
        336       0.370379    1.939537  1.070328  3.389316  1.426694
        720       0.419941    2.913707  1.275946  4.462837  1.706752
        Avg       0.357685    1.662133  0.917055  3.527659  1.457032
ETTh1   96        0.464985    1.028227  0.778285  0.951764  0.654582
        192       0.468557    1.009844  0.788853  0.877792  0.635419
        336       0.500309    0.907591  0.743380  0.889844  0.648006
        720       0.497544    0.987268  0.785309  0.910953  0.674663
        Avg       0.482849    0.983233  0.773957  0.907588  0.653168
ETTh2   96        0.396940    1.485310  0.959360  3.168482  1.362583
        192       0.470878    4.217736  1.585347  3.396996  1.470744
        336       0.469488    2.775491  1.360958  3.627431  1.556736
        720       0.501577    2.273706  1.256741  3.669120  1.575842
        Avg       0.459721    2.688061  1.290601  3.465508  1.491476
ECL     96        0.303782    0.253033  0.349768  0.680247  0.616512
        192       0.370508    0.261613  0.355824  0.579580  0.574237
        336       0.352282    0.269267  0.363271  0.583954  0.582005
        720       0.388354    0.276540  0.364641  0.599647  0.597977
        Avg       0.353731    0.265113  0.358376  0.610857  0.592683
Traffic 96        0.356492    0.689031  0.395804  1.392759  0.726703
        192       0.394140    0.709529  0.388488  0.802975  0.600374
        336       0.445912    0.686868  0.365756  0.817359  0.604844
        720       0.467833    0.680920  0.365594  0.858615  0.618925
        Avg       0.416094    0.691587  0.378910  0.967927  0.637712
Weather 96        0.305734    0.422590  0.447604  0.608333  0.565904
        192       0.347170    0.664421  0.585499  0.541347  0.551635
        336       0.385142    0.848319  0.685763  0.566715  0.568682
        720       0.420226    0.861086  0.684519  0.613383  0.597132
        Avg       0.364568    0.699104  0.600846  0.582444  0.570838
PEMS03  12        0.365566    0.105711  0.206221  0.618527  0.592885
        24        0.484931    0.117372  0.220804  0.643653  0.615916
        36        0.414909    0.127329  0.232790  0.667747  0.635393
        48        0.634450    0.139281  0.244868  0.685504  0.648265
        Avg       0.474964    0.122424  0.226171  0.653858  0.623115
PEMS08  12        0.334123    0.204328  0.231884  0.654921  0.584707
        24        0.550372    0.231600  0.251056  0.682478  0.606887
        36        0.436337    0.245666  0.262754  0.713476  0.627493
        48        0.501503    0.278337  0.297153  0.726231  0.634641
        Avg       0.455584    0.239983  0.260712  0.694277  0.613432

# Finetune

## load data

In [77]:
root = '/data/home/Licheng/workspace/TSF-PCA/results_PCA/finetune'
exp_dirs = os.listdir(root)
exp_dirs = [os.path.join(root, exp_dir) for exp_dir in exp_dirs]

params = ['model', 'seq_len', 'pred_len', 'data_id', 'learning_rate', 'rec_lambda', 'auxi_lambda', 'pca_dim', 'reinit', 'use_weights', 'rank_ratio', 'auxi_loss', 'batch_size', 'auxi_type', 'auxi_mode', 'lradj', 'patience', 'train_epochs']
metric_names = ['mse', 'mae']

df = []
for exp_dir in exp_dirs:
    runned, setting_dir = exist_metric(exp_dir)
    if not runned:
        continue

    config = load_yaml_as_df(os.path.join(setting_dir, 'config.yaml'))
    metric = load_npy(os.path.join(setting_dir, 'metrics.npy'))
    result = config[params]
    result.loc[:, metric_names] = metric[1], metric[0]
    result.loc[:, ['exp_dir']] = exp_dir
    df.append(result)

df = pd.concat(df, ignore_index=True)
df.sort_values(by=['model', 'data_id', 'pred_len'], inplace=True)

save_root = '/data/home/Licheng/workspace/TSF-PCA/stats_PCA'
df.to_csv(f"{save_root}/finetune_all_results.csv", index=False)

df.head(4)

KeyboardInterrupt:

## preprocess

In [72]:
df3 = df.copy()
# df3 = df3[
#     ((df3.model == 'FBM_L') & (df3.data_id.isin(['ETTh1_PCA', 'ETTh2_PCA', 'ETTm2_PCA']))) | \
#     ((df3.model == 'MICN') & (df3.data_id.isin(['ETTm1_PCA', 'PEMS03_PCA']))) | \
#     ((df3.model == 'iTransformer') & (df3.data_id.isin(['ECL_PCA', 'Traffic_PCA', 'PEMS08_PCA']))) | \
#     ((df3.model == 'FreTS') & (df3.data_id.isin(['Weather_PCA'])))
# ]
df3 = df3[
    (df3.seq_len == 96) & \
    df3.data_id.isin(['ETTh1_PCA', 'ETTh2_PCA', 'ETTm1_PCA', 'ETTm2_PCA', 'ECL_PCA', 'Traffic_PCA', 'Weather_PCA', 'PEMS03_PCA', 'PEMS08_PCA']) & \
    (df3.auxi_loss == 'MAE') & \
    (df3.reinit == 1) & \
    (df3.use_weights == 0) & \
    (df3.pca_dim == 'T')
]

columns = ['model', 'pred_len', 'data_id', 'learning_rate', 'alpha', 'pca_dim', 'reinit', 'use_weights', 'rank_ratio', 'auxi_loss', 'batch_size', 'auxi_type', 'auxi_mode', 'lradj', 'patience', 'train_epochs', 'exp_dir']
df3.rename(columns={'auxi_lambda': 'alpha'}, inplace=True)
df3 = df3[columns + ['mse', 'mae']]

## summary

In [73]:
min_mode = 'each'

df2 = df3.copy()

columns = ['model', 'data_id', 'learning_rate', 'alpha', 'rank_ratio', 'batch_size', 'lradj', 'patience', 'train_epochs', 'reinit', 'use_weights']
if min_mode == 'group':
    df2 = df2.groupby(columns).filter(is_full_group)
    mse_mean = df2.groupby(columns)['mse'].mean().reset_index()
    idx = mse_mean.groupby(['model', 'data_id'])['mse'].idxmin()
    best_model = mse_mean.loc[idx]
    df2 = df2.merge(best_model[columns], on=columns, how='inner')
elif min_mode == 'each':
    min_mse_idx = df2.groupby(['model', 'data_id', 'pred_len'])['mse'].idxmin()
    df2 = df2.loc[min_mse_idx]

columns = ['model', 'pred_len', 'data_id', 'mse', 'mae', 'learning_rate', 'alpha', 'pca_dim', 'reinit', 'use_weights', 'rank_ratio', 'auxi_loss', 'batch_size', 'auxi_type', 'auxi_mode', 'lradj', 'patience', 'train_epochs', 'exp_dir']
df2 = df2[columns]

dst_order = ['ETTm1_PCA', 'ETTm2_PCA', 'ETTh1_PCA', 'ETTh2_PCA', 'ECL_PCA', 'Traffic_PCA', 'Weather_PCA', 'PEMS03_PCA', 'PEMS08_PCA']
df2['data_id'] = pd.Categorical(df2['data_id'], categories=dst_order, ordered=True)

model_order = ['Fredformer', 'FBM_L', 'iTransformer', 'FreTS', 'TimesNet', 'MICN', 'TiDE', 'DLinear', 'DLinear_Ind', 'FEDformer', 'Autoformer', 'Transformer', 'TCN']
df2['model'] = pd.Categorical(df2['model'], categories=model_order, ordered=True)

df2_avg = df2.groupby(['model', 'data_id']).mean(numeric_only=True).reset_index()
df2_avg['pred_len'] = 'Avg'

df2 = pd.concat([df2, df2_avg]).reset_index(drop=True)
df2.sort_values(by=['data_id', 'model', 'pred_len'], inplace=True)

df2.dropna(inplace=True, thresh=5)

save_root = '/data/home/Licheng/workspace/TSF-PCA/stats_PCA'
os.makedirs(save_root, exist_ok=True)
df2.to_excel(f'{save_root}/best_finetune_full_{min_mode}.xlsx')
df2.to_csv(f'{save_root}/best_finetune_full_{min_mode}.csv', index=False)
df2

/tmp/ipykernel_3645157/3917441254.py:25: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df2_avg = df2.groupby(['model', 'data_id']).mean(numeric_only=True).reset_index()

,model,pred_len,data_id,mse,mae,learning_rate,alpha,pca_dim,reinit,use_weights,rank_ratio,auxi_loss,batch_size,auxi_type,auxi_mode,lradj,patience,train_epochs,exp_dir
84,Fredformer,96,ETTm1_PCA,0.321138,0.357436,0.000500,0.400,T,1.0,0.0,1.000,MAE,128.0,pca,basis,TST,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
85,Fredformer,192,ETTm1_PCA,0.359581,0.378119,0.000500,0.800,T,1.0,0.0,1.000,MAE,128.0,pca,basis,TST,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
86,Fredformer,336,ETTm1_PCA,0.389238,0.399987,0.000500,0.900,T,1.0,0.0,0.700,MAE,128.0,pca,basis,TST,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
87,Fredformer,720,ETTm1_PCA,0.447020,0.434891,0.000500,1.000,T,1.0,0.0,0.800,MAE,128.0,pca,basis,TST,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
152,Fredformer,Avg,ETTm1_PCA,0.379244,0.392608,0.000500,0.775,NaN,1.0,0.0,0.875,NaN,128.0,NaN,NaN,NaN,10.00,100.0,NaN
36,FBM_L,96,ETTm1_PCA,0.342714,0.364978,0.000500,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
37,FBM_L,192,ETTm1_PCA,0.387283,0.389597,0.000100,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
38,FBM_L,336,ETTm1_PCA,0.419475,0.410351,0.001000,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
39,FBM_L,720,ETTm1_PCA,0.481819,0.445778,0.000100,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
161,FBM_L,Avg,ETTm1_PCA,0.407823,0.402676,0.000425,1.000,NaN,1.0,0.0,1.000,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
128,iTransformer,96,ETTm1_PCA,0.323290,0.358108,0.000500,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
129,iTransformer,192,ETTm1_PCA,0.371106,0.388443,0.000500,0.800,T,1.0,0.0,0.400,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
130,iTransformer,336,ETTm1_PCA,0.407612,0.406701,0.000500,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
131,iTransformer,720,ETTm1_PCA,0.477105,0.449605,0.000500,0.800,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
170,iTransformer,Avg,ETTm1_PCA,0.394778,0.400714,0.000500,0.900,NaN,1.0,0.0,0.800,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
60,FreTS,96,ETTm1_PCA,0.325804,0.361129,0.001000,0.800,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
61,FreTS,192,ETTm1_PCA,0.374538,0.390776,0.000500,0.800,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
62,FreTS,336,ETTm1_PCA,0.406948,0.412794,0.000500,0.600,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
63,FreTS,720,ETTm1_PCA,0.488681,0.466158,0.000200,0.800,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
179,FreTS,Avg,ETTm1_PCA,0.398993,0.407714,0.000550,0.750,NaN,1.0,0.0,0.850,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
108,MICN,96,ETTm1_PCA,0.310823,0.360123,0.000100,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
109,MICN,192,ETTm1_PCA,0.354208,0.393495,0.000100,0.600,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
110,MICN,336,ETTm1_PCA,0.378588,0.413358,0.000100,0.600,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
111,MICN,720,ETTm1_PCA,0.425466,0.441101,0.000100,1.000,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
197,MICN,Avg,ETTm1_PCA,0.367271,0.402019,0.000100,0.800,NaN,1.0,0.0,0.800,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
12,DLinear,96,ETTm1_PCA,0.337609,0.363098,0.001000,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
13,DLinear,192,ETTm1_PCA,0.379070,0.387816,0.001000,0.600,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
14,DLinear,336,ETTm1_PCA,0.410564,0.409770,0.001000,0.800,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
15,DLinear,720,ETTm1_PCA,0.468786,0.443262,0.000500,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
215,DLinear,Avg,ETTm1_PCA,0.399007,0.400987,0.000875,0.850,NaN,1.0,0.0,0.600,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
88,Fredformer,96,ETTm2_PCA,0.172235,0.251189,0.000050,1.000,T,1.0,0.0,0.800,MAE,128.0,pca,basis,TST,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
89,Fredformer,192,ETTm2_PCA,0.235445,0.293936,0.000500,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,TST,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
90,Fredformer,336,ETTm2_PCA,0.293289,0.332727,0.000050,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,TST,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
91,Fredformer,720,ETTm2_PCA,0.387706,0.389056,0.000100,1.000,T,1.0,0.0,0.900,MAE,128.0,pca,basis,TST,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
153,Fredformer,Avg,ETTm2_PCA,0.272169,0.316727,0.000175,1.000,NaN,1.0,0.0,0.925,NaN,128.0,NaN,NaN,NaN,10.00,100.0,NaN
40,FBM_L,96,ETTm2_PCA,0.179471,0.259524,0.000100,0.400,T,1.0,0.0,0.100,MAE,64.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
41,FBM_L,192,ETTm2_PCA,0.244372,0.300326,0.000500,0.800,T,1.0,0.0,0.500,MAE,128.0,pca,basis,type1,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
42,FBM_L,336,ETTm2_PCA,0.304926,0.338215,0.000200,0.800,T,1.0,0.0,0.300,MAE,64.0,pca,basis,type1,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
43,FBM_L,720,ETTm2_PCA,0.405376,0.395003,0.000200,0.800,T,1.0,0.0,0.300,MAE,32.0,pca,basis,type1,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
162,FBM_L,Avg,ETTm2_PCA,0.283536,0.323267,0.000250,0.700,NaN,1.0,0.0,0.300,NaN,72.0,NaN,NaN,NaN,8.25,77.5,NaN
132,iTransformer,96,ETTm2_PCA,0.176744,0.257163,0.000500,0.600,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
133,iTransformer,192,ETTm2_PCA,0.240187,0.296751,0.000500,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
134,iTransformer,336,ETTm2_PCA,0.302232,0.338808,0.000500,0.800,T,1.0,0.0,0.100,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
135,iTransformer,720,ETTm2_PCA,0.402230,0.398479,0.000500,0.800,T,1.0,0.0,0.400,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
171,iTransformer,Avg,ETTm2_PCA,0.280348,0.322800,0.000500,0.800,NaN,1.0,0.0,0.375,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
64,FreTS,96,ETTm2_PCA,0.178253,0.261198,0.001000,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
65,FreTS,192,ETTm2_PCA,0.243733,0.308637,0.001000,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
66,FreTS,336,ETTm2_PCA,0.316074,0.367622,0.000200,0.800,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
67,FreTS,720,ETTm2_PCA,0.455674,0.446287,0.000500,0.800,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
180,FreTS,Avg,ETTm2_PCA,0.298434,0.345936,0.000675,0.900,NaN,1.0,0.0,0.650,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
16,DLinear,96,ETTm2_PCA,0.180199,0.266038,0.000500,0.800,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
17,DLinear,192,ETTm2_PCA,0.245143,0.308433,0.001000,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
18,DLinear,336,ETTm2_PCA,0.307494,0.354105,0.001000,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
19,DLinear,720,ETTm2_PCA,0.411193,0.421857,0.000500,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
216,DLinear,Avg,ETTm2_PCA,0.286007,0.337608,0.000750,0.950,NaN,1.0,0.0,0.700,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
76,Fredformer,96,ETTh1_PCA,0.368003,0.390765,0.000500,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
77,Fredformer,192,ETTh1_PCA,0.424089,0.421955,0.000500,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
78,Fredformer,336,ETTh1_PCA,0.466960,0.441356,0.000500,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
79,Fredformer,720,ETTh1_PCA,0.464932,0.463144,0.000500,1.000,T,1.0,0.0,0.900,MAE,128.0,pca,basis,type3,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
154,Fredformer,Avg,ETTh1_PCA,0.430996,0.429305,0.000500,1.000,NaN,1.0,0.0,0.975,NaN,128.0,NaN,NaN,NaN,10.00,100.0,NaN
28,FBM_L,96,ETTh1_PCA,0.379796,0.389360,0.000100,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
29,FBM_L,192,ETTh1_PCA,0.430838,0.420349,0.000100,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
30,FBM_L,336,ETTh1_PCA,0.470460,0.442433,0.000100,1.000,T,1.0,0.0,0.900,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
31,FBM_L,720,ETTh1_PCA,0.458959,0.459094,0.000200,1.000,T,1.0,0.0,0.800,MAE,64.0,pca,basis,type1,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
163,FBM_L,Avg,ETTh1_PCA,0.435013,0.427809,0.000125,1.000,NaN,1.0,0.0,0.925,NaN,40.0,NaN,NaN,NaN,6.50,55.0,NaN
120,iTransformer,96,ETTh1_PCA,0.377988,0.393197,0.000500,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
121,iTransformer,192,ETTh1_PCA,0.428025,0.422552,0.000500,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
122,iTransformer,336,ETTh1_PCA,0.472883,0.450154,0.000500,0.800,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
123,iTransformer,720,ETTh1_PCA,0.472567,0.468893,0.000500,0.800,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
172,iTransformer,Avg,ETTh1_PCA,0.437866,0.433699,0.000500,0.900,NaN,1.0,0.0,0.750,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
52,FreTS,96,ETTh1_PCA,0.379854,0.396190,0.001000,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
53,FreTS,192,ETTh1_PCA,0.435910,0.430698,0.000500,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
54,FreTS,336,ETTh1_PCA,0.488783,0.464087,0.000500,0.800,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
55,FreTS,720,ETTh1_PCA,0.539534,0.529846,0.000500,0.800,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
181,FreTS,Avg,ETTh1_PCA,0.461020,0.455205,0.000625,0.900,NaN,1.0,0.0,0.950,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
4,DLinear,96,ETTh1_PCA,0.377444,0.389328,0.001000,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
5,DLinear,192,ETTh1_PCA,0.427539,0.420120,0.001000,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
6,DLinear,336,ETTh1_PCA,0.469533,0.446173,0.001000,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
7,DLinear,720,ETTh1_PCA,0.485033,0.486940,0.001000,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
217,DLinear,Avg,ETTh1_PCA,0.439887,0.435640,0.001000,1.000,NaN,1.0,0.0,0.950,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
80,Fredformer,96,ETTh2_PCA,0.281609,0.330220,0.000050,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
81,Fredformer,192,ETTh2_PCA,0.359048,0.380537,0.000500,1.000,T,1.0,0.0,0.600,MAE,128.0,pca,basis,type3,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
82,Fredformer,336,ETTh2_PCA,0.393813,0.413791,0.000500,0.700,T,1.0,0.0,0.800,MAE,128.0,pca,basis,type3,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
83,Fredformer,720,ETTh2_PCA,0.400099,0.426993,0.000100,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
155,Fredformer,Avg,ETTh2_PCA,0.358642,0.387885,0.000287,0.925,NaN,1.0,0.0,0.850,NaN,128.0,NaN,NaN,NaN,10.00,100.0,NaN
32,FBM_L,96,ETTh2_PCA,0.286920,0.335147,0.000500,0.600,T,1.0,0.0,0.200,MAE,128.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
33,FBM_L,192,ETTh2_PCA,0.373026,0.388037,0.000500,0.400,T,1.0,0.0,0.100,MAE,128.0,pca,basis,type1,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
34,FBM_L,336,ETTh2_PCA,0.412747,0.422934,0.000200,0.100,T,1.0,0.0,0.100,MAE,64.0,pca,basis,type1,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
35,FBM_L,720,ETTh2_PCA,0.414799,0.434760,0.000100,0.200,T,1.0,0.0,0.100,MAE,32.0,pca,basis,type1,10.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
164,FBM_L,Avg,ETTh2_PCA,0.371873,0.395220,0.000325,0.325,NaN,1.0,0.0,0.125,NaN,88.0,NaN,NaN,NaN,8.25,77.5,NaN
124,iTransformer,96,ETTh2_PCA,0.285650,0.336500,0.000500,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
125,iTransformer,192,ETTh2_PCA,0.371956,0.389086,0.000500,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
126,iTransformer,336,ETTh2_PCA,0.410088,0.426113,0.000500,0.800,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
127,iTransformer,720,ETTh2_PCA,0.418333,0.440133,0.000500,0.800,T,1.0,0.0,0.400,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
173,iTransformer,Avg,ETTh2_PCA,0.371507,0.397958,0.000500,0.900,NaN,1.0,0.0,0.650,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
56,FreTS,96,ETTh2_PCA,0.296901,0.352660,0.000500,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
57,FreTS,192,ETTh2_PCA,0.396595,0.419860,0.000200,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
58,FreTS,336,ETTh2_PCA,0.474540,0.476513,0.000500,0.800,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
59,FreTS,720,ETTh2_PCA,0.647405,0.578132,0.001000,0.800,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
182,FreTS,Avg,ETTh2_PCA,0.453860,0.456791,0.000550,0.900,NaN,1.0,0.0,0.500,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
8,DLinear,96,ETTh2_PCA,0.294141,0.346018,0.001000,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
9,DLinear,192,ETTh2_PCA,0.385517,0.407372,0.001000,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
10,DLinear,336,ETTh2_PCA,0.452283,0.459334,0.000500,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
11,DLinear,720,ETTh2_PCA,0.568490,0.540306,0.000200,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
218,DLinear,Avg,ETTh2_PCA,0.425108,0.438257,0.000675,1.000,NaN,1.0,0.0,0.900,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
72,Fredformer,96,ECL_PCA,0.151151,0.244797,0.005000,0.800,T,1.0,0.0,0.800,MAE,32.0,pca,basis,TST,5.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
73,Fredformer,192,ECL_PCA,0.165649,0.256300,0.005000,1.000,T,1.0,0.0,1.000,MAE,32.0,pca,basis,TST,5.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
74,Fredformer,336,ECL_PCA,0.181096,0.274290,0.005000,0.800,T,1.0,0.0,0.600,MAE,32.0,pca,basis,TST,5.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
75,Fredformer,720,ECL_PCA,0.213155,0.304079,0.005000,1.000,T,1.0,0.0,0.600,MAE,32.0,pca,basis,TST,5.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
156,Fredformer,Avg,ECL_PCA,0.177763,0.269866,0.005000,0.900,NaN,1.0,0.0,0.750,NaN,32.0,NaN,NaN,NaN,5.00,100.0,NaN
24,FBM_L,96,ECL_PCA,0.197352,0.273545,0.001000,0.200,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
25,FBM_L,192,ECL_PCA,0.197122,0.276227,0.000200,0.200,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
26,FBM_L,336,ECL_PCA,0.211675,0.291472,0.000200,0.200,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
27,FBM_L,720,ECL_PCA,0.253316,0.324356,0.000200,0.200,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
165,FBM_L,Avg,ECL_PCA,0.214866,0.291400,0.000400,0.200,NaN,1.0,0.0,1.000,NaN,128.0,NaN,NaN,NaN,3.00,10.0,NaN
116,iTransformer,96,ECL_PCA,0.144906,0.234782,0.001000,0.800,T,1.0,0.0,1.000,MAE,16.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
117,iTransformer,192,ECL_PCA,0.158948,0.248666,0.001000,0.700,T,1.0,0.0,0.500,MAE,16.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
118,iTransformer,336,ECL_PCA,0.173076,0.264487,0.001000,0.800,T,1.0,0.0,1.000,MAE,16.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
119,iTransformer,720,ECL_PCA,0.203276,0.292044,0.001000,0.800,T,1.0,0.0,0.300,MAE,16.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
174,iTransformer,Avg,ECL_PCA,0.170051,0.259995,0.001000,0.775,NaN,1.0,0.0,0.700,NaN,16.0,NaN,NaN,NaN,3.00,10.0,NaN
48,FreTS,96,ECL_PCA,0.178489,0.262438,0.001000,0.600,T,1.0,0.0,0.600,MAE,16.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
49,FreTS,192,ECL_PCA,0.182575,0.268897,0.001000,0.600,T,1.0,0.0,0.600,MAE,16.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
50,FreTS,336,ECL_PCA,0.196722,0.285411,0.001000,0.600,T,1.0,0.0,0.200,MAE,16.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
51,FreTS,720,ECL_PCA,0.232992,0.318748,0.001000,0.600,T,1.0,0.0,0.200,MAE,16.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
183,FreTS,Avg,ECL_PCA,0.197694,0.283874,0.001000,0.600,NaN,1.0,0.0,0.400,NaN,16.0,NaN,NaN,NaN,3.00,10.0,NaN
0,DLinear,96,ECL_PCA,0.194632,0.275993,0.001000,0.600,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
1,DLinear,192,ECL_PCA,0.193919,0.279426,0.001000,0.600,T,1.0,0.0,1.000,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
2,DLinear,336,ECL_PCA,0.206861,0.294570,0.001000,0.600,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
3,DLinear,720,ECL_PCA,0.242502,0.328900,0.001000,0.600,T,1.0,0.0,0.800,MAE,32.0,pca,basis,type1,3.00,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
219,DLinear,Avg,ECL_PCA,0.209478,0.294722,0.001000,0.600,NaN,1.0,0.0,0.900,NaN,32.0,NaN,NaN,NaN,3.00,10.0,NaN
100,Fredformer,96,Traffic_PCA,0.388514,0.256442,0.005000,1.000,T,1.0,0.0,0.800,MAE,32.0,pca,basis,TST,5.00,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...

## long term forecasting final results

In [74]:
df4 = df2.copy()

df4 = df4[
    ((df4.model == 'Fredformer') & (df4.data_id == 'ETTm1_PCA')) | \
    ((df4.model == 'Fredformer') & (df4.data_id == 'ETTm2_PCA')) | \
    ((df4.model == 'Fredformer') & (df4.data_id == 'ETTh1_PCA')) | \
    ((df4.model == 'Fredformer') & (df4.data_id == 'ETTh2_PCA')) | \
    ((df4.model == 'iTransformer') & (df4.data_id == 'ECL_PCA')) | \
    ((df4.model == 'iTransformer') & (df4.data_id == 'Traffic_PCA')) | \
    ((df4.model == 'FreTS') & (df4.data_id == 'Weather_PCA')) | \
    ((df4.model == 'MICN') & (df4.data_id == 'PEMS03_PCA')) | \
    ((df4.model == 'iTransformer') & (df4.data_id == 'PEMS08_PCA'))
]

os.makedirs(save_root, exist_ok=True)
df4.to_excel(f'{save_root}/best_finetune_{min_mode}_params.xlsx')
df4.to_csv(f'{save_root}/best_finetune_{min_mode}_params.csv', index=False)
df4

,model,pred_len,data_id,mse,mae,learning_rate,alpha,pca_dim,reinit,use_weights,rank_ratio,auxi_loss,batch_size,auxi_type,auxi_mode,lradj,patience,train_epochs,exp_dir
84,Fredformer,96,ETTm1_PCA,0.321138,0.357436,0.000500,0.400,T,1.0,0.0,1.000,MAE,128.0,pca,basis,TST,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
85,Fredformer,192,ETTm1_PCA,0.359581,0.378119,0.000500,0.800,T,1.0,0.0,1.000,MAE,128.0,pca,basis,TST,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
86,Fredformer,336,ETTm1_PCA,0.389238,0.399987,0.000500,0.900,T,1.0,0.0,0.700,MAE,128.0,pca,basis,TST,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
87,Fredformer,720,ETTm1_PCA,0.447020,0.434891,0.000500,1.000,T,1.0,0.0,0.800,MAE,128.0,pca,basis,TST,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
152,Fredformer,Avg,ETTm1_PCA,0.379244,0.392608,0.000500,0.775,NaN,1.0,0.0,0.875,NaN,128.0,NaN,NaN,NaN,10.0,100.0,NaN
88,Fredformer,96,ETTm2_PCA,0.172235,0.251189,0.000050,1.000,T,1.0,0.0,0.800,MAE,128.0,pca,basis,TST,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
89,Fredformer,192,ETTm2_PCA,0.235445,0.293936,0.000500,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,TST,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
90,Fredformer,336,ETTm2_PCA,0.293289,0.332727,0.000050,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,TST,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
91,Fredformer,720,ETTm2_PCA,0.387706,0.389056,0.000100,1.000,T,1.0,0.0,0.900,MAE,128.0,pca,basis,TST,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
153,Fredformer,Avg,ETTm2_PCA,0.272169,0.316727,0.000175,1.000,NaN,1.0,0.0,0.925,NaN,128.0,NaN,NaN,NaN,10.0,100.0,NaN
76,Fredformer,96,ETTh1_PCA,0.368003,0.390765,0.000500,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
77,Fredformer,192,ETTh1_PCA,0.424089,0.421955,0.000500,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
78,Fredformer,336,ETTh1_PCA,0.466960,0.441356,0.000500,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
79,Fredformer,720,ETTh1_PCA,0.464932,0.463144,0.000500,1.000,T,1.0,0.0,0.900,MAE,128.0,pca,basis,type3,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
154,Fredformer,Avg,ETTh1_PCA,0.430996,0.429305,0.000500,1.000,NaN,1.0,0.0,0.975,NaN,128.0,NaN,NaN,NaN,10.0,100.0,NaN
80,Fredformer,96,ETTh2_PCA,0.281609,0.330220,0.000050,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
81,Fredformer,192,ETTh2_PCA,0.359048,0.380537,0.000500,1.000,T,1.0,0.0,0.600,MAE,128.0,pca,basis,type3,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
82,Fredformer,336,ETTh2_PCA,0.393813,0.413791,0.000500,0.700,T,1.0,0.0,0.800,MAE,128.0,pca,basis,type3,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
83,Fredformer,720,ETTh2_PCA,0.400099,0.426993,0.000100,1.000,T,1.0,0.0,1.000,MAE,128.0,pca,basis,type3,10.0,100.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
155,Fredformer,Avg,ETTh2_PCA,0.358642,0.387885,0.000287,0.925,NaN,1.0,0.0,0.850,NaN,128.0,NaN,NaN,NaN,10.0,100.0,NaN
116,iTransformer,96,ECL_PCA,0.144906,0.234782,0.001000,0.800,T,1.0,0.0,1.000,MAE,16.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
117,iTransformer,192,ECL_PCA,0.158948,0.248666,0.001000,0.700,T,1.0,0.0,0.500,MAE,16.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
118,iTransformer,336,ECL_PCA,0.173076,0.264487,0.001000,0.800,T,1.0,0.0,1.000,MAE,16.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
119,iTransformer,720,ECL_PCA,0.203276,0.292044,0.001000,0.800,T,1.0,0.0,0.300,MAE,16.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
174,iTransformer,Avg,ECL_PCA,0.170051,0.259995,0.001000,0.775,NaN,1.0,0.0,0.700,NaN,16.0,NaN,NaN,NaN,3.0,10.0,NaN
144,iTransformer,96,Traffic_PCA,0.392572,0.264985,0.001000,0.800,T,1.0,0.0,1.000,MAE,8.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
145,iTransformer,192,Traffic_PCA,0.409847,0.274966,0.001000,0.600,T,1.0,0.0,0.600,MAE,8.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
146,iTransformer,336,Traffic_PCA,0.420893,0.280186,0.001000,0.800,T,1.0,0.0,0.600,MAE,8.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
147,iTransformer,720,Traffic_PCA,0.450731,0.298500,0.001000,0.200,T,1.0,0.0,0.600,MAE,8.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
175,iTransformer,Avg,Traffic_PCA,0.418511,0.279659,0.001000,0.600,NaN,1.0,0.0,0.700,NaN,8.0,NaN,NaN,NaN,3.0,10.0,NaN
68,FreTS,96,Weather_PCA,0.169180,0.218550,0.001000,0.400,T,1.0,0.0,0.100,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
69,FreTS,192,Weather_PCA,0.210151,0.257542,0.001000,0.500,T,1.0,0.0,0.100,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
70,FreTS,336,Weather_PCA,0.258569,0.297079,0.001000,0.900,T,1.0,0.0,0.300,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
71,FreTS,720,Weather_PCA,0.327103,0.348704,0.001000,0.800,T,1.0,0.0,0.300,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
185,FreTS,Avg,Weather_PCA,0.241251,0.280469,0.001000,0.650,NaN,1.0,0.0,0.200,NaN,32.0,NaN,NaN,NaN,3.0,10.0,NaN
112,MICN,12,PEMS03_PCA,0.069891,0.176210,0.000500,1.000,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
113,MICN,24,PEMS03_PCA,0.087064,0.198136,0.000500,0.600,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
114,MICN,36,PEMS03_PCA,0.105463,0.219407,0.000500,0.600,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
115,MICN,48,PEMS03_PCA,0.123658,0.238285,0.000500,0.600,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
204,MICN,Avg,PEMS03_PCA,0.096519,0.208009,0.000500,0.700,NaN,1.0,0.0,0.400,NaN,32.0,NaN,NaN,NaN,3.0,10.0,NaN
140,iTransformer,12,PEMS08_PCA,0.081086,0.183092,0.001000,0.200,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
141,iTransformer,24,PEMS08_PCA,0.117261,0.217823,0.001000,0.600,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
142,iTransformer,36,PEMS08_PCA,0.156879,0.252824,0.001000,0.600,T,1.0,0.0,0.200,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
143,iTransformer,48,PEMS08_PCA,0.207103,0.294117,0.001000,0.600,T,1.0,0.0,0.600,MAE,32.0,pca,basis,type1,3.0,10.0,/data/home/Licheng/workspace/TSF-PCA/results_P...
178,iTransformer,Avg,PEMS08_PCA,0.140582,0.236964,0.001000,0.500,NaN,1.0,0.0,0.300,NaN,32.0,NaN,NaN,NaN,3.0,10.0,NaN

# Merge

## load data

In [75]:
save_root = '/data/home/Licheng/workspace/TSF-PCA/stats_PCA'
baselines = pd.read_csv(f'{save_root}/baselines_params.csv')
finetunes = pd.read_csv(f'{save_root}/best_finetune_each_params.csv')

model_list = ['Fredformer', 'iTransformer', 'FreTS', 'TimesNet', 'MICN', 'TiDE', 'DLinear', 'FEDformer', 'Autoformer', 'Transformer']

base = baselines.copy()
base = base[base.model.isin(model_list)]

best = finetunes.copy()
best['model'] = 'PDF'
best['data_id'] = best['data_id'].str.replace('_PCA', '')
best = best[best.pred_len != 'Avg']

columns = ['model', 'pred_len', 'data_id', 'mse', 'mae']
df2 = pd.concat([base[columns], best[columns]], ignore_index=True)
df2['pred_len'] = df2['pred_len'].astype(int)

dst_order = ['ETTm1', 'ETTm2', 'ETTh1', 'ETTh2', 'ECL', 'Traffic', 'Weather', 'PEMS03', 'PEMS08']
df2['data_id'] = pd.Categorical(df2['data_id'], categories=dst_order, ordered=True)

model_order = ['PDF', 'Fredformer', 'iTransformer', 'FreTS', 'TimesNet', 'MICN', 'TiDE', 'DLinear', 'FEDformer', 'Autoformer', 'Transformer']
df2['model'] = pd.Categorical(df2['model'], categories=model_order, ordered=True)

df2_avg = df2.groupby(['model', 'data_id']).mean(numeric_only=True).reset_index()
df2_avg['pred_len'] = 'Avg'
df2 = pd.concat([df2, df2_avg]).reset_index(drop=True)

df2.sort_values(by=['model', 'data_id', 'pred_len'], inplace=True)

df2 = df2.set_index(['data_id', 'pred_len', 'model']).unstack('model').swaplevel(axis=1)
columns = []
for model in df2.columns.levels[0]:
    columns.append((model, 'mse'))
    columns.append((model, 'mae'))
df2 = df2[columns]

df2.round(3).to_csv(f'{save_root}/long_term_results.csv', float_format='%.3f')
df2.round(4)

/tmp/ipykernel_3645157/2837928657.py:25: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df2_avg = df2.groupby(['model', 'data_id']).mean(numeric_only=True).reset_index()

model                PDF         Fredformer         iTransformer          \
                     mse     mae        mse     mae          mse     mae
data_id pred_len
ETTm1   96        0.3211  0.3574     0.3264  0.3609       0.3379  0.3723
        192       0.3596  0.3781     0.3652  0.3821       0.3817  0.3961
        336       0.3892  0.4000     0.3960  0.4044       0.4270  0.4240
        720       0.4470  0.4349     0.4592  0.4443       0.4958  0.4626
        Avg       0.3792  0.3926     0.3867  0.3979       0.4106  0.4137
ETTm2   96        0.1722  0.2512     0.1770  0.2599       0.1820  0.2647
        192       0.2354  0.2939     0.2416  0.2997       0.2570  0.3148
        336       0.2933  0.3327     0.3018  0.3402       0.3199  0.3540
        720       0.3877  0.3891     0.3988  0.3967       0.4225  0.4114
        Avg       0.2722  0.3167     0.2798  0.3241       0.2954  0.3362
ETTh1   96        0.3680  0.3908     0.3772  0.3959       0.3852  0.4053
        192       0.4241  0.4220     0.4370  0.4254       0.4405  0.4368
        336       0.4670  0.4414     0.4858  0.4486       0.4799  0.4572
        720       0.4649  0.4631     0.4878  0.4674       0.5035  0.4916
        Avg       0.4310  0.4293     0.4469  0.4343       0.4523  0.4477
ETTh2   96        0.2816  0.3302     0.2934  0.3439       0.3013  0.3492
        192       0.3590  0.3805     0.3720  0.3912       0.3830  0.3972
        336       0.3938  0.4138     0.4204  0.4335       0.4249  0.4323
        720       0.4001  0.4270     0.4207  0.4392       0.4363  0.4485
        Avg       0.3586  0.3879     0.3766  0.4019       0.3864  0.4068
ECL     96        0.1449  0.2348     0.1610  0.2576       0.1500  0.2415
        192       0.1589  0.2487     0.1736  0.2695       0.1681  0.2591
        336       0.1731  0.2645     0.1941  0.2904       0.1823  0.2744
        720       0.2033  0.2920     0.2347  0.3194       0.2145  0.3035
        Avg       0.1701  0.2600     0.1908  0.2842       0.1787  0.2696
Traffic 96        0.3926  0.2650     0.4606  0.3272       0.3966  0.2712
        192       0.4098  0.2750     0.4695  0.3258       0.4158  0.2789
        336       0.4209  0.2802     0.4918  0.3383       0.4294  0.2860
        720       0.4507  0.2985     0.5213  0.3528       0.4622  0.3028
        Avg       0.4185  0.2797     0.4858  0.3360       0.4260  0.2847
Weather 96        0.1692  0.2185     0.1802  0.2198       0.1714  0.2105
        192       0.2102  0.2575     0.2224  0.2576       0.2464  0.2783
        336       0.2586  0.2971     0.2835  0.3010       0.2962  0.3130
        720       0.3271  0.3487     0.3577  0.3485       0.3623  0.3528
        Avg       0.2413  0.2805     0.2609  0.2817       0.2691  0.2886
PEMS03  12        0.0699  0.1762     0.0805  0.1913       0.0722  0.1792
        24        0.0871  0.1981     0.1209  0.2396       0.1042  0.2167
        36        0.1055  0.2194     0.1803  0.2925       0.1373  0.2513
        48        0.1237  0.2383     0.2015  0.3157       0.1737  0.2847
        Avg       0.0965  0.2080     0.1458  0.2598       0.1218  0.2330
PEMS08  12        0.0811  0.1831     0.0907  0.1987       0.0837  0.1870
        24        0.1173  0.2178     0.1381  0.2455       0.1232  0.2269
        36        0.1569  0.2528     0.1992  0.3033       0.1697  0.2681
        48        0.2071  0.2941     0.2548  0.3383       0.2181  0.3061
        Avg       0.1406  0.2370     0.1707  0.2714       0.1487  0.2470

model              FreTS         TimesNet            MICN            TiDE  \
                     mse     mae      mse     mae     mse     mae     mse
data_id pred_len
ETTm1   96        0.3418  0.3746   0.3676  0.3943  0.3195  0.3655  0.3529
        192       0.3845  0.4004   0.4060  0.4092  0.3644  0.3954  0.3911
        336       0.4160  0.4206   0.4536  0.4438  0.3953  0.4253  0.4234
        720       0.5133  0.4892   0.5267  0.4743  0.5055  0.4988  0.4857
        Avg       0.4139  0.4212   0.4385  0.4304  0.3961  0.4213  0.4133
ETTm2   96        0.1884  0.2787   0.1844  0.2620  0.1784  0.2769  0.1822
        192       0.2642  0.3291   0.2570  0.3084  0.2662  0.3430  0.2465
        336       0.3224  0.3692   0.3145  0.3448  0.2989  0.3542  0.3074
        720       0.4890  0.4815   0.4521  0.4214  0.4893  0.4816  0.4077
        Avg       0.3160  0.3646   0.3020  0.3341  0.3082  0.3639  0.2859
ETTh1   96        0.3982  0.4093   0.3989  0.4184  0.3813  0.4161  0.3869
        192       0.4509  0.4425   0.4525  0.4506  0.4975  0.4885  0.4387
        336       0.5006  0.4716   0.4880  0.4689  0.5886  0.5553  0.4818
        720       0.6077  0.5707   0.5493  0.5147  0.6649  0.6171  0.4837
        Avg       0.4893  0.4735   0.4721  0.4632  0.5331  0.5192  0.4477
ETTh2   96        0.3153  0.3736   0.3207  0.3581  0.3510  0.3976  0.2908
        192       0.4661  0.4666   0.4179  0.4173  0.4923  0.4887  0.3762
        336       0.5217  0.5019   0.4639  0.4542  0.6560  0.5816  0.4168
        720       0.7920  0.6426   0.4343  0.4496  0.9806  0.7177  0.4294
        Avg       0.5238  0.4962   0.4092  0.4198  0.6200  0.5464  0.3783
ECL     96        0.1799  0.2663   0.1696  0.2722  0.1703  0.2812  0.1975
        192       0.1842  0.2725   0.1829  0.2822  0.1847  0.2974  0.1973
        336       0.1992  0.2897   0.2027  0.3019  0.1898  0.2980  0.2119
        720       0.2344  0.3219   0.2938  0.3660  0.2214  0.3294  0.2538
        Avg       0.1994  0.2876   0.2122  0.3056  0.1916  0.3015  0.2151
Traffic 96        0.5314  0.3233   0.5900  0.3161  0.4985  0.2983  0.6463
        192       0.5185  0.3214   0.6243  0.3364  0.5206  0.3092  0.5992
        336       0.5292  0.3274   0.6413  0.3452  0.5295  0.3140  0.6058
        720       0.5732  0.3460   0.6702  0.3564  0.5673  0.3262  0.6428
        Avg       0.5381  0.3295   0.6315  0.3385  0.5290  0.3119  0.6235
Weather 96        0.1737  0.2277   0.1828  0.2292  0.1788  0.2442  0.1916
        192       0.2128  0.2661   0.2421  0.2762  0.2419  0.3101  0.2398
        336       0.2705  0.3159   0.2927  0.3116  0.2729  0.3302  0.2925
        720       0.3372  0.3623   0.3665  0.3614  0.3603  0.3991  0.3643
        Avg       0.2486  0.2930   0.2710  0.2946  0.2635  0.3209  0.2721
PEMS03  12        0.0853  0.1977   0.0941  0.2015  0.0962  0.2170  0.1169
        24        0.1290  0.2437   0.1161  0.2206  0.0949  0.2096  0.2333
        36        0.1730  0.2859   0.1338  0.2367  0.1070  0.2229  0.3789
        48        0.2069  0.3151   0.1614  0.2615  0.1248  0.2422  0.5351
        Avg       0.1485  0.2606   0.1264  0.2301  0.1057  0.2229  0.3160
PEMS08  12        0.0962  0.2052   0.1111  0.2085  0.1610  0.2742  0.1210
        24        0.1506  0.2583   0.1386  0.2318  0.1266  0.2370  0.2324
        36        0.2031  0.3029   0.1683  0.2598  0.1479  0.2521  0.3763
        48        0.2469  0.3344   0.1889  0.2719  0.1746  0.2696  0.5434
        Avg       0.1742  0.2752   0.1517  0.2430  0.1525  0.2582  0.3183

model                    DLinear         FEDformer         Autoformer          \
                     mae     mse     mae       mse     mae        mse     mae
data_id pred_len
ETTm1   96        0.3742  0.3458  0.3734    0.4008  0.4337     0.4853  0.4684
        192       0.3926  0.3803  0.3899    0.4149  0.4464     0.5044  0.4820
        336       0.4137  0.4132  0.4139    0.4318  0.4496     0.5196  0.4894
        720       0.4479  0.4717  0.4499    0.5224  0.5001     0.5941  0.5234
        Avg       0.4071  0.4028  0.4068    0.4425  0.4574     0.5259  0.4908
ETTm2   96        0.2650  0.1879  0.2829    0.2055  0.2891     0.2177  0.3000
        192       0.3042  0.2797  0.3558    0.2707  0.3344     0.2820  0.3404
        336       0.3429  0.3754  0.4203    0.3272  0.3659     0.3355  0.3704
        720       0.3982  0.5258  0.5081    0.4277  0.4252     0.4230  0.4199
        Avg       0.3276  0.3422  0.3918    0.3078  0.3537     0.3145  0.3577
ETTh1   96        0.3950  0.3889  0.4037    0.3910  0.4329     0.4487  0.4650
        192       0.4247  0.4422  0.4399    0.4177  0.4483     0.4586  0.4686
        336       0.4470  0.4885  0.4666    0.4871  0.4844     0.5106  0.5003
        720       0.4714  0.5051  0.5024    0.4942  0.5137     0.4881  0.4975
        Avg       0.4345  0.4562  0.4531    0.4475  0.4698     0.4765  0.4828
ETTh2   96        0.3398  0.3300  0.3826    0.3514  0.3908     0.3554  0.3969
        192       0.3916  0.4392  0.4495    0.4562  0.4557     0.4784  0.4709
        336       0.4274  0.5894  0.5375    0.4771  0.4917     0.4587  0.4695
        720       0.4456  0.7572  0.6262    0.5222  0.5054     0.4994  0.5016
        Avg       0.4011  0.5289  0.4990    0.4517  0.4609     0.4480  0.4597
ECL     96        0.2740  0.1970  0.2824    0.1867  0.3021     0.1885  0.3038
        192       0.2768  0.1966  0.2856    0.2069  0.3219     0.2709  0.3705
        336       0.2918  0.2095  0.3009    0.2106  0.3265     0.2428  0.3523
        720       0.3251  0.2448  0.3335    0.2525  0.3614     0.2948  0.3884
        Avg       0.2919  0.2120  0.3006    0.2142  0.3280     0.2492  0.3537
Traffic 96        0.3855  0.6489  0.3966    0.5882  0.3669     0.5746  0.3565
        192       0.3616  0.5985  0.3709    0.6135  0.3768     0.6471  0.3941
        336       0.3631  0.6052  0.3733    0.6395  0.3977     0.6939  0.4459
        720       0.3825  0.6458  0.3954    0.7178  0.4500     0.7313  0.4678
        Avg       0.3732  0.6246  0.3840    0.6398  0.3979     0.6617  0.4161
Weather 96        0.2324  0.1940  0.2532    0.2345  0.3101     0.2326  0.3057
        192       0.2702  0.2379  0.2963    0.2949  0.3528     0.2855  0.3472
        336       0.3068  0.2818  0.3320    0.3641  0.3968     0.3461  0.3851
        720       0.3532  0.3475  0.3849    0.4111  0.4285     0.4117  0.4202
        Avg       0.2906  0.2653  0.3166    0.3262  0.3721     0.3190  0.3646
PEMS03  12        0.2258  0.1050  0.2204    0.1085  0.2286     0.2328  0.3656
        24        0.3220  0.1829  0.2969    0.1309  0.2546     0.4052  0.4849
        36        0.4177  0.2577  0.3613    0.1592  0.2850     0.3272  0.4149
        48        0.5162  0.3187  0.4102    0.2091  0.3310     0.6794  0.6345
        Avg       0.3704  0.2161  0.3222    0.1519  0.2748     0.4112  0.4750
PEMS08  12        0.2333  0.1130  0.2252    0.1625  0.2577     0.2317  0.3341
        24        0.3251  0.1987  0.3021    0.1971  0.2876     0.5446  0.5504
        36        0.4270  0.2945  0.3706    0.2412  0.3262     0.3786  0.4363
        48        0.5266  0.3889  0.4285    0.3020  0.3751     0.5311  0.5015
        Avg       0.3780  0.2488  0.3316    0.2257  0.3117     0.4215  0.4556

model            Transformer
                         mse     mae
data_id pred_len
ETTm1   96            0.5029  0.4815
        192           0.8070  0.6640
        336           0.8472  0.6776
        720           1.0374  0.7707
        Avg           0.7986  0.6484
ETTm2   96            0.3857  0.4408
        192           1.4096  0.8812
        336           1.9395  1.0703
        720           2.9137  1.2759
        Avg           1.6621  0.9171
ETTh1   96            1.0282  0.7783
        192           1.0098  0.7889
        336           0.9076  0.7434
        720           0.9873  0.7853
        Avg           0.9832  0.7740
ETTh2   96            1.4853  0.9594
        192           4.2177  1.5853
        336           2.7755  1.3610
        720           2.2737  1.2567
        Avg           2.6881  1.2906
ECL     96            0.2530  0.3498
        192           0.2616  0.3558
        336           0.2693  0.3633
        720           0.2765  0.3646
        Avg           0.2651  0.3584
Traffic 96            0.6890  0.3958
        192           0.7095  0.3885
        336           0.6869  0.3658
        720           0.6809  0.3656
        Avg           0.6916  0.3789
Weather 96            0.4226  0.4476
        192           0.6644  0.5855
        336           0.8483  0.6858
        720           0.8611  0.6845
        Avg           0.6991  0.6008
PEMS03  12            0.1057  0.2062
        24            0.1174  0.2208
        36            0.1273  0.2328
        48            0.1393  0.2449
        Avg           0.1224  0.2262
PEMS08  12            0.2043  0.2319
        24            0.2316  0.2511
        36            0.2457  0.2628
        48            0.2783  0.2972
        Avg           0.2400  0.2607

In [76]:
df2a = df2_avg.copy()


df2a = df2a.set_index(['data_id', 'pred_len', 'model']).unstack('model').swaplevel(axis=1)
columns = []
for model in df2a.columns.levels[0]:
    columns.append((model, 'mse'))
    columns.append((model, 'mae'))
df2a = df2a[columns]

df2a.round(3).to_csv(f'{save_root}/long_term_results_avg.csv', float_format='%.3f')
df2a

model                  PDF           Fredformer           iTransformer  \
                       mse       mae        mse       mae          mse
data_id pred_len
ETTm1   Avg       0.379244  0.392608   0.386692  0.397928     0.410572
ETTm2   Avg       0.272169  0.316727   0.279835  0.324134     0.295358
ETTh1   Avg       0.430996  0.429305   0.446938  0.434302     0.452279
ETTh2   Avg       0.358642  0.387885   0.376599  0.401924     0.386392
ECL     Avg       0.170051  0.259995   0.190846  0.284211     0.178736
Traffic Avg       0.418511  0.279659   0.485811  0.336030     0.426009
Weather Avg       0.241251  0.280469   0.260930  0.281717     0.269089
PEMS03  Avg       0.096519  0.208009   0.145803  0.259755     0.121839
PEMS08  Avg       0.140582  0.236964   0.170704  0.271440     0.148672

model                          FreTS            TimesNet                MICN  \
                       mae       mse       mae       mse       mae       mse
data_id pred_len
ETTm1   Avg       0.413716  0.413916  0.421182  0.438483  0.430418  0.396142
ETTm2   Avg       0.336203  0.315991  0.364634  0.301994  0.334121  0.308182
ETTh1   Avg       0.447707  0.489336  0.473515  0.472139  0.463155  0.533093
ETTh2   Avg       0.406793  0.523777  0.496169  0.409188  0.419780  0.619974
ECL     Avg       0.269609  0.199420  0.287601  0.212249  0.305589  0.191564
Traffic Avg       0.284707  0.538091  0.329537  0.631450  0.338492  0.528958
Weather Avg       0.288630  0.248560  0.293011  0.271045  0.294599  0.263501
PEMS03  Avg       0.232957  0.148539  0.260600  0.126363  0.230071  0.105705
PEMS08  Avg       0.247042  0.174184  0.275201  0.151745  0.242988  0.152543

model                           TiDE             DLinear           FEDformer  \
                       mae       mse       mae       mse       mae       mse
data_id pred_len
ETTm1   Avg       0.421255  0.413294  0.407082  0.402787  0.406771  0.442489
ETTm2   Avg       0.363925  0.285932  0.327573  0.342181  0.391771  0.307774
ETTh1   Avg       0.519238  0.447741  0.434524  0.456173  0.453143  0.447485
ETTh2   Avg       0.546394  0.378299  0.401092  0.528937  0.498962  0.451734
ECL     Avg       0.301516  0.215127  0.291933  0.211973  0.300595  0.214211
Traffic Avg       0.311916  0.623523  0.373185  0.624593  0.384049  0.639760
Weather Avg       0.320877  0.272055  0.290650  0.265288  0.316614  0.326166
PEMS03  Avg       0.222944  0.316045  0.370418  0.216076  0.322211  0.151928
PEMS08  Avg       0.258241  0.318261  0.378022  0.248770  0.331627  0.225699

model                      Autoformer           Transformer
                       mae        mse       mae         mse       mae
data_id pred_len
ETTm1   Avg       0.457431   0.525861  0.490807    0.798614  0.648424
ETTm2   Avg       0.353655   0.314520  0.357685    1.662133  0.917055
ETTh1   Avg       0.469822   0.476525  0.482849    0.983233  0.773957
ETTh2   Avg       0.460887   0.447956  0.459721    2.688061  1.290601
ECL     Avg       0.327979   0.249238  0.353731    0.265113  0.358376
Traffic Avg       0.397865   0.661691  0.416094    0.691587  0.378910
Weather Avg       0.372051   0.318987  0.364568    0.699104  0.600846
PEMS03  Avg       0.274800   0.411156  0.474964    0.122424  0.226171
PEMS08  Avg       0.311668   0.421538  0.455584    0.239983  0.260712