# Imports

In [24]:
import os
import pickle
import re
import shutil
import sys
sys.path.append(os.path.dirname(os.getcwd()))
from itertools import product
from scipy.stats import norm
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import yaml
from matplotlib.backends.backend_pdf import PdfPages
from tools import load_npy, load_yaml_as_df, load_pkl, exist_metric, exist_stf_metric, inverse_stf_metrics, keep_split, is_full_group

plt.style.use('default')
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42
plt.rc('font', family='Arial')
matplotlib.rcParams['mathtext.fontset'] = 'stix'
matplotlib.rcParams['font.size'] = 10

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Varying input length

## load data

In [27]:
root = '/data/home/Licheng/workspace/TSF-PCA/results_PCA/vary_input'
exp_dirs = os.listdir(root)
exp_dirs = [os.path.join(root, exp_dir) for exp_dir in exp_dirs]

params = ['model', 'seq_len', 'pred_len', 'data_id', 'learning_rate', 'rec_lambda', 'auxi_lambda', 'pca_dim', 'reinit', 'use_weights', 'rank_ratio', 'auxi_loss', 'batch_size', 'auxi_type', 'auxi_mode', 'lradj', 'patience', 'train_epochs']
metric_names = ['mse', 'mae']

df = []
for exp_dir in exp_dirs:
    runned, setting_dir = exist_metric(exp_dir)
    if not runned:
        continue

    config = load_yaml_as_df(os.path.join(setting_dir, 'config.yaml'))
    metric = load_npy(os.path.join(setting_dir, 'metrics.npy'))
    result = config[params]
    result.loc[:, metric_names] = metric[1], metric[0]
    result.loc[:, ['exp_dir']] = exp_dir
    df.append(result)

df = pd.concat(df, ignore_index=True)
df.sort_values(by=['model', 'data_id', 'seq_len', 'pred_len'], inplace=True)
df.head(4)

,model,seq_len,pred_len,data_id,learning_rate,rec_lambda,auxi_lambda,pca_dim,reinit,use_weights,rank_ratio,auxi_loss,batch_size,auxi_type,auxi_mode,lradj,patience,train_epochs,mse,mae,exp_dir
1056,FreTS,192,96,Weather,0.0005,1.0,0.0,all,0,0,1.0,MAE,32,complex,fft,type1,3,10,0.158995,0.213995,/data/home/Licheng/workspace/TSF-PCA/results_P...
387,FreTS,192,192,Weather,0.0005,1.0,0.0,all,0,0,1.0,MAE,32,complex,fft,type1,3,10,0.201555,0.256462,/data/home/Licheng/workspace/TSF-PCA/results_P...
777,FreTS,192,336,Weather,0.0005,1.0,0.0,all,0,0,1.0,MAE,32,complex,fft,type1,3,10,0.250179,0.297790,/data/home/Licheng/workspace/TSF-PCA/results_P...
382,FreTS,192,720,Weather,0.0005,1.0,0.0,all,0,0,1.0,MAE,32,complex,fft,type1,3,10,0.320959,0.350454,/data/home/Licheng/workspace/TSF-PCA/results_P...

## preprocess

In [28]:
save_root = '/data/home/Licheng/workspace/TSF-PCA/stats_PCA'

baselines = pd.read_csv(f'{save_root}/baselines_params.csv')
finetunes_best = pd.read_csv(f'{save_root}/best_finetune_full_each.csv')

base = baselines.copy()
base = base[
    ((base.data_id == 'Weather') & (base.model == 'iTransformer'))
]
base['seq_len'] = 96
base['label'] = 'DF'

best = finetunes_best.copy()
best = best[
    ((best.data_id == 'Weather_PCA') & (best.model == 'iTransformer'))
]
best['seq_len'] = 96
best['label'] = 'PDF'
best = best[best.pred_len != 'Avg']
best['data_id'] = best['data_id'].str.replace('_PCA', '')


df2 = df.copy()
df2 = df2[
    ((df2.seq_len != 96) & (df2.model == 'iTransformer') & (df2.data_id.isin(['Weather', 'Weather_PCA']))) |
    ((df2.model == 'PatchTST') & (df2.data_id.isin(['Weather', 'Weather_PCA'])))
]

min_mse_idx = df2.groupby(['model', 'data_id', 'seq_len', 'pred_len'])['mse'].idxmin()
df2 = df2.loc[min_mse_idx]
df2['label'] = df2['data_id'].apply(lambda x: 'PDF' if "_PCA" in x else 'DF')
df2['data_id'] = df2['data_id'].str.replace('_PCA', '')

columns = ['model', 'data_id', 'seq_len', 'pred_len', 'label', 'mse', 'mae']
vary_seq = pd.concat([base[columns], best[columns], df2[columns]], ignore_index=True)
vary_seq['seq_len'] = vary_seq['seq_len'].astype(int)
vary_seq['pred_len'] = vary_seq['pred_len'].astype(int)

dst_order = ['Weather']
vary_seq['data_id'] = pd.Categorical(vary_seq['data_id'], categories=dst_order, ordered=True)

model_order = ['iTransformer', 'PatchTST']
vary_seq['model'] = pd.Categorical(vary_seq['model'], categories=model_order, ordered=True)


vary_seq_avg = vary_seq.groupby(['model', 'data_id', 'seq_len', 'label']).mean(numeric_only=True).reset_index()
vary_seq_avg['pred_len'] = 'Avg'
vary_seq = pd.concat([vary_seq, vary_seq_avg], ignore_index=True)

# sl_order = ['96', '192', '336', '720']
# vary_seq['seq_len'] = pd.Categorical(vary_seq['seq_len'], categories=sl_order, ordered=True)

# pl_order = ['96', '192', '336', '720', 'Avg']
# vary_seq['pred_len'] = pd.Categorical(vary_seq['pred_len'], categories=pl_order, ordered=True)

vary_seq.sort_values(by=['model', 'data_id', 'seq_len', 'label', 'pred_len'], inplace=True)

save_root = '/data/home/Licheng/workspace/TSF-PCA/stats_PCA'
vary_seq.round(3).to_csv(f'{save_root}/vary_seq.csv', index=False, float_format='%.3f')
vary_seq

/tmp/ipykernel_751009/1151328204.py:46: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  vary_seq_avg = vary_seq.groupby(['model', 'data_id', 'seq_len', 'label']).mean(numeric_only=True).reset_index()

           model  data_id  seq_len pred_len label       mse       mae
0   iTransformer  Weather       96       96    DF  0.171432  0.210468
1   iTransformer  Weather       96      192    DF  0.246395  0.278306
2   iTransformer  Weather       96      336    DF  0.296230  0.312968
3   iTransformer  Weather       96      720    DF  0.362297  0.352779
64  iTransformer  Weather       96      Avg    DF  0.269089  0.288630
4   iTransformer  Weather       96       96   PDF  0.162750  0.201556
5   iTransformer  Weather       96      192   PDF  0.213842  0.247811
6   iTransformer  Weather       96      336   PDF  0.273705  0.293638
7   iTransformer  Weather       96      720   PDF  0.351255  0.344143
65  iTransformer  Weather       96      Avg   PDF  0.250388  0.271787
40  iTransformer  Weather      192       96    DF  0.168018  0.214745
41  iTransformer  Weather      192      192    DF  0.213063  0.252877
42  iTransformer  Weather      192      336    DF  0.265174  0.293507
43  iTransformer  Weather      192      720    DF  0.341313  0.345142
66  iTransformer  Weather      192      Avg    DF  0.246892  0.276568
52  iTransformer  Weather      192       96   PDF  0.163065  0.204749
53  iTransformer  Weather      192      192   PDF  0.209689  0.248087
54  iTransformer  Weather      192      336   PDF  0.259171  0.287255
55  iTransformer  Weather      192      720   PDF  0.333863  0.337959
67  iTransformer  Weather      192      Avg   PDF  0.241447  0.269512
44  iTransformer  Weather      336       96    DF  0.162260  0.212622
45  iTransformer  Weather      336      192    DF  0.210901  0.255815
46  iTransformer  Weather      336      336    DF  0.260062  0.295159
47  iTransformer  Weather      336      720    DF  0.332233  0.341377
68  iTransformer  Weather      336      Avg    DF  0.241364  0.276243
56  iTransformer  Weather      336       96   PDF  0.156650  0.203118
57  iTransformer  Weather      336      192   PDF  0.199045  0.245679
58  iTransformer  Weather      336      336   PDF  0.250902  0.286528
59  iTransformer  Weather      336      720   PDF  0.323755  0.337835
69  iTransformer  Weather      336      Avg   PDF  0.232588  0.268290
48  iTransformer  Weather      720       96    DF  0.171849  0.224676
49  iTransformer  Weather      720      192    DF  0.220288  0.267842
50  iTransformer  Weather      720      336    DF  0.281930  0.310717
51  iTransformer  Weather      720      720    DF  0.337355  0.351348
70  iTransformer  Weather      720      Avg    DF  0.252856  0.288646
60  iTransformer  Weather      720       96   PDF  0.161000  0.212707
61  iTransformer  Weather      720      192   PDF  0.204743  0.250415
62  iTransformer  Weather      720      336   PDF  0.254189  0.292239
63  iTransformer  Weather      720      720   PDF  0.318386  0.339087
71  iTransformer  Weather      720      Avg   PDF  0.234579  0.273612
8       PatchTST  Weather       96       96    DF  0.199959  0.244120
9       PatchTST  Weather       96      192    DF  0.229160  0.262790
10      PatchTST  Weather       96      336    DF  0.286948  0.302729
11      PatchTST  Weather       96      720    DF  0.362553  0.352860
72      PatchTST  Weather       96      Avg    DF  0.269655  0.290624
24      PatchTST  Weather       96       96   PDF  0.174815  0.213118
25      PatchTST  Weather       96      192   PDF  0.223850  0.257382
26      PatchTST  Weather       96      336   PDF  0.276422  0.296104
27      PatchTST  Weather       96      720   PDF  0.353195  0.346074
73      PatchTST  Weather       96      Avg   PDF  0.257070  0.278169
12      PatchTST  Weather      192       96    DF  0.163508  0.208106
13      PatchTST  Weather      192      192    DF  0.224504  0.269482
14      PatchTST  Weather      192      336    DF  0.287070  0.308364
15      PatchTST  Weather      192      720    DF  0.340683  0.344928
74      PatchTST  Weather      192      Avg    DF  0.253941  0.282720
28      PatchTST  Weather      192       96   PDF  0.158029  0.199282
29      PatchTST  Weather      192      192   PDF  0.203828  0.242003
30      PatchTST  Weather      192      336   PDF  0.257465  0.285883
31      PatchTST  Weather      192      720   PDF  0.331893  0.336830
75      PatchTST  Weather      192      Avg   PDF  0.237804  0.265999
16      PatchTST  Weather      336       96    DF  0.155737  0.206056
17      PatchTST  Weather      336      192    DF  0.222281  0.277065
18      PatchTST  Weather      336      336    DF  0.251308  0.285381
19      PatchTST  Weather      336      720    DF  0.327426  0.338250
76      PatchTST  Weather      336      Avg    DF  0.239188  0.276688
32      PatchTST  Weather      336       96   PDF  0.150157  0.196049
33      PatchTST  Weather      336      192   PDF  0.195909  0.241290
34      PatchTST  Weather      336      336   PDF  0.245571  0.281511
35      PatchTST  Weather      336      720   PDF  0.319725  0.332729
77      PatchTST  Weather      336      Avg   PDF  0.227840  0.262894
20      PatchTST  Weather      720       96    DF  0.154029  0.207052
21      PatchTST  Weather      720      192    DF  0.204703  0.254449
22      PatchTST  Weather      720      336    DF  0.248361  0.288291
23      PatchTST  Weather      720      720    DF  0.317180  0.338526
78      PatchTST  Weather      720      Avg    DF  0.231068  0.272079
36      PatchTST  Weather      720       96   PDF  0.151688  0.201103
37      PatchTST  Weather      720      192   PDF  0.197604  0.247622
38      PatchTST  Weather      720      336   PDF  0.247727  0.284291
39      PatchTST  Weather      720      720   PDF  0.313282  0.334613
79      PatchTST  Weather      720      Avg   PDF  0.227575  0.266907